app:
  webserver: false
  port: 80
ntfy: 
  allowed: true
  url: http://10.0.0.189
  topic: niftyhogramofon
  icon: https://raw.githubusercontent.com/NiftyBuffalo619/NiftysGramofonDiscord/main/mainicon.png
googlesheets: # Allows you to store data in a googlesheets file
  allowed: true